//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMark370MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Book_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_Request()
        {
            this.Book_Request_Line = new HashSet<Book_Request_Line>();
        }
    
        public int Book_Request_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        [Display(Name ="Book Title")]
        [Required(AllowEmptyStrings =false, ErrorMessage ="Book title required")]
        public string Book_Title { get; set; }
        [Display(Name = "Book Author")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Book author required")]
        public string Book_Author { get; set; }
        [Display(Name = "Book Edition")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Book edition required")]
        public string Book_Edition { get; set; }
        [Display(Name = "Book Request")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Book request details required")]
        public string Book_Request_Description { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Surname { get; set; }
        public string Customer_Phone { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Request_Line> Book_Request_Line { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
