//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMark370MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Payment_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment_Type()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int PaymentType_ID { get; set; }
        [Display(Name = "Payment Type Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Payment type name required")]
        public string PaymentType_Name { get; set; }
        [Display(Name = "Payment Type Description")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Payment type description required")]
        public string PaymentType_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
